### ISSUE TITLE
http对应的divide插件，能否做服务发现

### ISSUE THREAD

**Issue by plm479104792** [dromara/soul#399]
divide插件，服务上线之后，需要手动去后台添加ip:端口。增减机器、集群模式能否做下 服务自动发现。
手动配置太繁琐了

**Comment by yu199195** [comment]
客户端不是有注册吗

**Comment by plm479104792** [comment]
> 客户端不是有注册吗

我想表达的意思是，类似springcloud动态注册自己的服务，不需要去在soul-admin后台上填ip:端口号

客户端注册，只是注册了基础的selector、rule，但是没有把自己的ip:端口号 给到soul-admin。
客户端上线之后，需要手动去后台找到对应的selector, 在selector上添加ip:端口。

**Comment by yu199195** [comment]
仔细看下客户端那块 不是有个配置, 这ip地址不就上去了吗？
```
soul:
  http:
    adminUrl: http://localhost:9095
    port: 8187
    contextPath: /http
    appName: http 
```
